"use client";
import { useState } from "react";
type View="fleet"|"request"|"dispatch";
const aircraft=[
{id:"N172MN",type:"Cessna 172S",name:"North Star",state:"Available",meta:"Brainerd · 4 seats",hrs:"46 hr",due:"100-hour inspection",tone:"green",icon:"✈"},
{id:"N612ML",type:"Cessna 172S",name:"Lakes Country",state:"In flight",meta:"Returning 2:40 PM",hrs:"31 hr",due:"Oil service",tone:"blue",icon:"✈"},
{id:"N208MN",type:"Kodiak 100",name:"Timberwolf",state:"Available",meta:"Bemidji · 10 seats",hrs:"18 hr",due:"Phase inspection",tone:"green",icon:"➤"},
{id:"N839RM",type:"Robinson R44",name:"Canopy",state:"Maintenance",meta:"Expected Aug 20",hrs:"Due now",due:"50-hour inspection",tone:"sand",icon:"✣"}];
const requests=[
{initials:"LM",name:"Leah M.",route:"KBRD → North Shore Nursery",time:"Today · 1:30 PM",aircraft:"N612ML",status:"In flight",color:"blue"},
{initials:"JT",name:"Jordan T.",route:"KBRD → Red Lake Project",time:"Tomorrow · 7:00 AM",aircraft:"N208MN",status:"Ready",color:"green"},
{initials:"AP",name:"Avery P.",route:"KBRD → Duluth",time:"Aug 21 · 9:15 AM",aircraft:"Unassigned",status:"Review",color:"sand"}];
const pilots=[{name:"Mara Jensen",initials:"MJ",qualification:"C172 · Kodiak",state:"On duty",accent:"green"},{name:"Eli Redbird",initials:"ER",qualification:"C172 · R44",state:"Available",accent:"blue"},{name:"Nolan Chen",initials:"NC",qualification:"C172",state:"Reserve",accent:"sand"}];

export default function Home(){const[view,setView]=useState<View>("fleet");const[step,setStep]=useState(1);const[submitted,setSubmitted]=useState(false);const[permission,setPermission]=useState(true);const[pilot,setPilot]=useState("Mara Jensen");const[toast,setToast]=useState("");const notify=(s:string)=>{setToast(s);window.setTimeout(()=>setToast(""),2400)};return <main>
<header className="topbar"><button className="brand" onClick={()=>setView("fleet")}><span className="brandMark">MN</span><span><strong>Minnesota Native</strong><small>Flight Operations</small></span></button><nav className="desktopNav">{(["fleet","request","dispatch"]as View[]).map(v=><button key={v} className={view===v?"active":""} onClick={()=>setView(v)}>{v==="fleet"?"Fleet":v==="request"?"My requests":"Dispatch"}</button>)}</nav><div className="topActions"><span>Demo data</span><button className="avatar">JS</button></div></header>
<div className="syncNote"><span>◎</span><p><strong>Back-office demo only</strong> <em>Flight Schedule Pro may be considered as a future source of operational data. It is not connected.</em></p><b>Potential future connection</b></div>
{view==="fleet"&&<Fleet onRequest={()=>{setView("request");setStep(1);setSubmitted(false)}} onDispatch={()=>setView("dispatch")}/>} {view==="request"&&<Request step={step} setStep={setStep} submitted={submitted} setSubmitted={setSubmitted} notify={notify}/>} {view==="dispatch"&&<Dispatch pilot={pilot} setPilot={setPilot} permission={permission} setPermission={setPermission} notify={notify}/>} 
<nav className="mobileNav"><button className={view==="fleet"?"active":""} onClick={()=>setView("fleet")}><span>⌂</span>Fleet</button><button className={view==="request"?"active":""} onClick={()=>setView("request")}><span>＋</span>Request</button><button className={view==="dispatch"?"active":""} onClick={()=>setView("dispatch")}><span>↗</span>Dispatch</button></nav>{toast&&<div className="toast">✓ {toast}</div>}</main>}

function Fleet({onRequest,onDispatch}:{onRequest:()=>void;onDispatch:()=>void}){return <div className="pageShell"><section className="hero"><div><p className="eyebrow">Tuesday, August 18</p><h1>Good morning, Joe.</h1><p>Your fleet is ready for today’s field work.</p></div><button className="primaryButton" onClick={onRequest}>＋ Flight Request</button></section>
<section className="metrics"><Metric icon="✈" value="3" label="Aircraft operational" tone="green"/><Metric icon="↗" value="2" label="Flights today" tone="blue"/><Metric icon="⌁" value="1" label="Maintenance alert" tone="sand"/><Metric icon="◷" value="12 / 18" label="Pilot days remaining" tone="mint"/></section>
<div className="sectionHeading"><div><h2>Fleet status</h2><p>Live sample availability across your aircraft</p></div><span>● Updated just now</span></div><section className="aircraftGrid">{aircraft.map(a=><article className="aircraftCard" key={a.id}><div className={`aircraftVisual ${a.tone}`}><span className="tail">{a.id}</span><span className="planeIcon">{a.icon}</span><span className={`statusBadge ${a.tone}`}>● {a.state}</span></div><div className="aircraftBody"><p className="overline">{a.type}</p><h3>{a.name}</h3><p className="location">⌖ {a.meta}</p><div className="maintenance"><span>◇</span><p><small>Next maintenance</small><strong>{a.due}</strong></p><b className={a.hrs==="Due now"?"urgent":""}>{a.hrs}</b></div></div></article>)}</section>
<section className="splitSection"><div className="panel"><div className="panelHead"><div><h2>Upcoming flights</h2><p>Next 7 days</p></div><button onClick={onDispatch}>Open dispatch →</button></div>{requests.map(r=><div className="requestRow" key={r.name}><span className={`initials ${r.color}`}>{r.initials}</span><div><strong>{r.name}</strong><small>{r.time}</small></div><div className="route"><strong>{r.route}</strong><small>{r.aircraft}</small></div><span className={`miniStatus ${r.color}`}>● {r.status}</span></div>)}</div>
<div className="panel pilotPanel"><div className="panelHead"><div><h2>Pilot bench</h2><p>Built-in coverage, every trip</p></div><span className="coverage">3 ready</span></div><p className="continuity">A qualified second pilot is kept in the loop on every assignment, so your plans keep moving when schedules change.</p><div className="pilotList">{pilots.map(p=><div key={p.name}><span className={`initials ${p.accent}`}>{p.initials}</span><p><strong>{p.name}</strong><small>{p.qualification}</small></p><span className={`dot ${p.accent}`}>● {p.state}</span></div>)}</div><div className="pilotDays"><div><span>◷</span><p><strong>Included pilot days</strong><small>August service plan</small></p><b>12 remaining</b></div><div className="progress"><i/></div><small>6 of 18 days used</small></div></div></section></div>}
function Metric({icon,value,label,tone}:{icon:string;value:string;label:string;tone:string}){return <div><span className={`metricIcon ${tone}`}>{icon}</span><p><strong>{value}</strong><small>{label}</small></p></div>}

function Request({step,setStep,submitted,setSubmitted,notify}:{step:number;setStep:(n:number)=>void;submitted:boolean;setSubmitted:(v:boolean)=>void;notify:(s:string)=>void}){if(submitted)return <div className="pageShell narrow"><section className="successCard"><span className="successIcon">✓</span><p className="eyebrow">Request MN-1048</p><h1>Flight request received</h1><p>Operations will confirm the aircraft, qualified pilot, and landing-site permission. You’ll see every update here.</p><div className="timeline"><Timeline n="✓" title="Request submitted" detail="Today, 10:42 AM" cls="done"/><Timeline n="2" title="Operations review" detail="Aircraft, pilot, and site checks" cls="current"/><Timeline n="3" title="Flight confirmed" detail="You’ll be notified when ready"/></div><button className="secondaryButton" onClick={()=>{setSubmitted(false);setStep(1)}}>Create another request</button></section></div>;return <div className="pageShell narrow"><section className="requestIntro"><p className="eyebrow">Employee flight request</p><h1>Where does the work take you?</h1><p>Share the trip basics. Operations will handle the aircraft, pilot, and landing details.</p></section><div className="stepper"><span className={step>=1?"on":""}>1<b>Trip</b></span><i className={step>=2?"on":""}/><span className={step>=2?"on":""}>2<b>Passengers</b></span><i className={step>=3?"on":""}/><span className={step>=3?"on":""}>3<b>Review</b></span></div><section className="formCard">{step===1&&<FormOne/>}{step===2&&<FormTwo/>}{step===3&&<Review/>}<div className="formActions"><button className="secondaryButton" disabled={step===1} onClick={()=>setStep(step-1)}>Back</button><button className="primaryButton" onClick={()=>step<3?setStep(step+1):(setSubmitted(true),notify("Request submitted"))}>{step<3?"Continue":"Submit request"} →</button></div></section></div>}
function FormHead({n,title,sub}:{n:string;title:string;sub:string}){return <div className="formTitle"><span>{n}</span><div><h2>{title}</h2><p>{sub}</p></div></div>}
function FormOne(){return <><FormHead n="01" title="Trip details" sub="Tell us where and when."/><div className="formGrid"><label>Departing from<select defaultValue="Brainerd Regional (KBRD)"><option>Brainerd Regional (KBRD)</option><option>Bemidji Regional (KBJI)</option></select></label><label>Destination<input defaultValue="Red Lake project site"/></label><label>Departure date<input type="date" defaultValue="2026-08-20"/></label><label>Preferred time<input type="time" defaultValue="07:00"/></label><label className="wide">Purpose of trip<textarea defaultValue="Field leadership visit and native planting review"/></label></div></>}
function FormTwo(){return <><FormHead n="02" title="Passengers & gear" sub="Help us choose the right aircraft."/><div className="formGrid"><label>Number of travelers<select defaultValue="3"><option>1</option><option>2</option><option>3</option><option>4</option><option>5–8</option></select></label><label>Estimated gear weight<select defaultValue="Under 100 lb"><option>Under 50 lb</option><option>Under 100 lb</option><option>100–250 lb</option></select></label><label className="wide">Traveler names<input defaultValue="Joe Schafer, Leah M., Jordan T."/></label><label className="wide check"><input type="checkbox" defaultChecked/> I’ll need transportation from the landing site</label></div></>}
function Review(){return <><FormHead n="03" title="Review request" sub="Operations will confirm the final plan."/><div className="reviewBlock"><div><small>Route</small><strong>Brainerd → Red Lake project site</strong></div><div><small>Departure</small><strong>Thu, Aug 20 · 7:00 AM</strong></div><div><small>Travelers</small><strong>3 people · under 100 lb gear</strong></div><div><small>Purpose</small><strong>Field leadership visit</strong></div></div><div className="infoBox">ℹ Aircraft and pilot appear after operations confirms qualification, availability, and landing permission.</div></>}
function Timeline({n,title,detail,cls=""}:{n:string;title:string;detail:string;cls?:string}){return <div className={cls}><i>{n}</i><p><strong>{title}</strong><small>{detail}</small></p></div>}

function Dispatch({pilot,setPilot,permission,setPermission,notify}:{pilot:string;setPilot:(s:string)=>void;permission:boolean;setPermission:(v:boolean)=>void;notify:(s:string)=>void}){return <div className="pageShell"><section className="hero compact"><div><p className="eyebrow">Operations workspace</p><h1>Dispatch review</h1><p>Confirm the people, aircraft, and place before release.</p></div><span className="opsBadge">Operations view</span></section><section className="dispatchLayout"><div className="dispatchMain">
<article className="panel dispatchRequest"><div className="dispatchTitle"><div><span className="miniStatus sand">● Owner approved</span><h2>Brainerd → Red Lake project site</h2><p>Request MN-1048 · Joe Schafer</p></div><div className="dateTile"><strong>20</strong><small>AUG</small></div></div><div className="tripFacts"><span><small>Departure</small><strong>7:00 AM</strong></span><span><small>Travelers</small><strong>3 people</strong></span><span><small>Gear</small><strong>&lt; 100 lb</strong></span><span><small>Return</small><strong>Same day</strong></span></div></article>
<article className="panel assignment"><NumberHead n="1" title="Aircraft assignment" sub="Matched to mission requirements"/><div className="choiceCard"><span className="choiceIcon">➤</span><div><p className="overline">KODIAK 100 · N208MN</p><h3>Timberwolf</h3><small>Best fit for passengers, gear, and remote-site access</small></div><span className="checkRound">✓</span></div></article>
<article className="panel assignment"><NumberHead n="2" title="Qualified pilot" sub="Select primary assignment"/><div className="pilotChoices">{pilots.slice(0,2).map(p=><button key={p.name} className={pilot===p.name?"selected":""} onClick={()=>setPilot(p.name)}><span className={`initials ${p.accent}`}>{p.initials}</span><p><strong>{p.name}</strong><small>{p.qualification}</small></p><i>{pilot===p.name?"✓":""}</i></button>)}</div><div className="benchNote"><span>↻</span><p><strong>Continuity covered</strong><small>{pilot==="Mara Jensen"?"Eli Redbird":"Mara Jensen"} is briefed as the qualified backup pilot.</small></p></div></article>
<article className="panel assignment"><NumberHead n="3" title="Landing-site permission" sub="Required before dispatch"/><button className={`permission ${permission?"approved":""}`} onClick={()=>setPermission(!permission)}><span>{permission?"✓":"!"}</span><p><strong>{permission?"Permission verified":"Permission required"}</strong><small>Red Lake project site · Landowner confirmation on file</small></p><b>{permission?"Approved":"Review"}</b></button></article></div>
<aside className="releaseCard"><p className="eyebrow">Release checklist</p><h2>Ready to confirm</h2><div className="releaseList"><p><span>✓</span> Request reviewed</p><p><span>✓</span> Aircraft available</p><p><span>✓</span> Pilot qualified</p><p className={!permission?"pending":""}><span>{permission?"✓":"!"}</span> Landing permission</p></div><div className="weather"><span>☀</span><p><strong>Weather outlook</strong><small>VFR · 72° · light winds</small></p></div><button className="primaryButton full" disabled={!permission} onClick={()=>notify("Flight MN-1048 confirmed")}>Confirm & release flight</button><small className="disclaimer">Demo only. Final operational release remains with the operator and its approved systems.</small></aside></section></div>}
function NumberHead({n,title,sub}:{n:string;title:string;sub:string}){return <div className="numberedHead"><span>{n}</span><div><h2>{title}</h2><p>{sub}</p></div>{n==="1"&&<b>Recommended</b>}</div>}
